spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.93.37.94:33306/sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:    #rabbitMQ消息队列配置
    host: 39.105.162.160
    port: 5672
    username: guest
    password: guest  
  jpa:
    show-sql: true
  redis:
    host: 47.93.37.94
    port: 6379  
env: dev
girl:
  name: 520000+52000000
